// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.0
//   protoc               v5.27.2
// source: proto/messages.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "messages";

export interface TransmitMessageRequest {
  id: number;
  message: string;
}

export interface TransmitMessageResponse {
  status: number;
  error: string[];
  id: number;
  message: string;
}

export const MESSAGES_PACKAGE_NAME = "messages";

export interface MessagesServiceClient {
  transmitMessage(request: TransmitMessageRequest): Observable<TransmitMessageResponse>;
}

export interface MessagesServiceController {
  transmitMessage(
    request: TransmitMessageRequest,
  ): Promise<TransmitMessageResponse> | Observable<TransmitMessageResponse> | TransmitMessageResponse;
}

export function MessagesServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["transmitMessage"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("MessagesService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("MessagesService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const MESSAGES_SERVICE_NAME = "MessagesService";
